/* eslint-disable import/no-anonymous-default-export */
export default {
  formId: "admissionForm",
  formField: {
    surname: {
      name: "surname",
      label: "Surname",
      placeholder: "Surname",
      requiredErrorMsg: "Surname is required",
    },
    firstName: {
      name: "firstName",
      label: "First Name",
      placeholder: "First Name",
      requiredErrorMsg: "First Name is required",
    },
    middleName: {
      name: "middleName",
      label: "Middle Name",
      placeholder: "Enter your middle name",
    },
    email: {
      name: "email",
      label: "Email",
      placeholder: "Enter your email",
      requiredErrorMsg: "Email is required",
    },
    dateOfBirth: {
      name: "dateOfBirth",
      label: "Date of Birth",
      placeholder: "DD/MM/YYYY",
      requiredErrorMsg: "Date of birth is required",
    },
    gender: {
      name: "gender",
      label: "Gender",
      placeholder: "Choose your gender",
      requiredErrorMsg: "Gender is required",
    },
    age: {
      name: "age",
      label: "Age",
      placeholder: "Enter your age",
      requiredErrorMsg: "Age is required",
    },
    placeOfBirth: {
      name: "placeOfBirth",
      label: "Place of Birth",
      placeholder: "Enter your place of birth",
      requiredErrorMsg: "Place of birth is required",
    },
    phoneNumber: {
      name: "phoneNumber",
      label: "Phone Number",
      requiredErrorMsg: "Phone Number is required",
    },
    nationality: {
      name: "nationality",
      label: "Nationality",
      placeholder: "Enter your Nationality",
      requiredErrorMsg: "Nationality is required",
    },
    stateOfOrigin: {
      name: "stateOfOrigin",
      label: "State Of Origin",
      placeholder: "Where is your state of Origin",
      requiredErrorMsg: "State Of Origin is required",
    },
    town: {
      name: "town",
      label: "Town",
      placeholder: "Where is your town located",
      requiredErrorMsg: "Town is required",
    },
    classCategory: {
      name: "classCategory",
      label: "Class Category",
      placeholder: "Class Category",
      requiredErrorMsg: "Class Category is required",
    },
    address: {
      name: "address",
      label: "Address",
      placeholder: "Enter your address",
      requiredErrorMsg: "Address is required",
    },
    fatherName: {
      name: "fatherName",
      label: "Father/Guardian's Name",
      placeholder: "Father Name",
      requiredErrorMsg: "Father Name is required",
    },
    fatherOccupation: {
      name: "fatherOccupation",
      label: "Father/Guardian's Occupation",
      placeholder: "Occupation",
      requiredErrorMsg: "Father Occupation is required",
    },
    fatherReligion: {
      name: "fatherReligion",
      label: "Father/Guardian's Religion",
      placeholder: "Religion",
      requiredErrorMsg: "Father Religion is required",
    },
    fatherPhoneNumber: {
      name: "fatherPhoneNumber",
      label: "Father/Guardian's Phone Number",
      requiredErrorMsg: "Father/Guardian's Phone Number is required",
    },
    motherName: {
      name: "motherName",
      label: "Mother's Name",
      placeholder: "Mother Name",
      requiredErrorMsg: "Mother Name is required",
    },
    motherOccupation: {
      name: "motherOccupation",
      label: "Mother's Occupation",
      placeholder: "Occupation",
      requiredErrorMsg: "Mother Occupation is required",
    },
    motherReligion: {
      name: "motherReligion",
      label: "Mother's Religion",
      placeholder: "Religion",
      requiredErrorMsg: "Mother Religion is required",
    },
    motherPhoneNumber: {
      name: "motherPhoneNumber",
      label: "Mother's Phone Number",
      requiredErrorMsg: "Mother's Phone Number is required",
    },
    denominationName: {
      name: "denominationName",
      label: "Name of Denomination",
      placeholder: "Enter your church denomination",
      requiredErrorMsg: "Church denomination is required",
    },
    denominationAddress: {
      name: "denominationAddress",
      label: "Address of Denomination",
      placeholder: "Enter the address of your denomination",
      requiredErrorMsg: "Address denomination is required",
    },
    parentsBornAgain: {
      name: "parentsBornAgain",
      label: "Are parents/Guardian's born again?",
      placeholder: "Yes/No",
      requiredErrorMsg: "Are parents born again is required",
    },
    objectionPreaching: {
      name: "objectionPreaching",
      label: "Any objection by parents to preaching JESUS to child/ward?",
      placeholder: "Enter answer here",
      requiredErrorMsg: "Any objection to preach is required",
    },
    enrollmentReason: {
      name: "enrollmentReason",
      label: "Why are you enrolling your child in Dayspring Academy?",
      placeholder: "Enter answer here",
      requiredErrorMsg: "Reason for enrollment is required",
    },
    pastorName: {
      name: "pastorName",
      label: "Pastor's Name",
      placeholder: "Pastor's Name",
      requiredErrorMsg: "Pastor's Name is required",
    },
    lastSchool: {
      name: "lastSchool",
      label: "Name of school last attended",
      placeholder: "Enter name of school last attended",
      requiredErrorMsg: "Name of school is required",
    },
    schoolAddress: {
      name: "schoolAddress",
      label: "Address of school",
      placeholder: "Entere address of school last attended",
      requiredErrorMsg: "Address of school is required",
    },
    lastClassPassed: {
      name: "lastClassPassed",
      label: "Class last passed",
      placeholder: "Select class last passed",
      requiredErrorMsg: "Last class is required",
    },
    presentClass: {
      name: "presentClass",
      label: "Present Class",
      placeholder: "Select present class",
      requiredErrorMsg: "Present class is required",
    },
    specialInterest: {
      name: "specialInterest",
      label: "Special Interests/Hobbies",
      placeholder: "Enter what your interest/hobbies are",
      requiredErrorMsg: "Interest/Hobbies is required",
    },
    academicGoal: {
      name: "academicGoal",
      label: "Academic Goal",
      placeholder: "Enter your academic goal",
      requiredErrorMsg: "Academic is required",
    },
    reasonChangingSchool: {
      name: "reasonChangingSchool",
      label: "State briefly your reason for changing schools",
      placeholder: "Enter answer here",
      requiredErrorMsg: "Field is required",
    },
    disciplinaryDifficulty: {
      name: "disciplinaryDifficulty",
      label:
        "Did the student face any disciplinary difficulty in their previous school? If yes, what was it?",
      placeholder: "Enter answer here",
      requiredErrorMsg: "Field is required",
    },
    academicDifficulty: {
      name: "academicDifficulty",
      label: "Does the student have any academic difficulty? ",
      placeholder: "Enter answer here",
      requiredErrorMsg: "Field is required",
    },
    emotionalChallenge: {
      name: "emotionalChallenge",
      label:
        "Does the student have any physical or emotional challenge that may affect their attendance?",
      placeholder: "Enter answer here",
      requiredErrorMsg: "Field is required",
    },
  },
};
